# Generated by Django 3.2.23 on 2023-12-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_mingle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
