# Generated by Django 3.2.23 on 2023-12-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_mingle_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='ads', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
