# Generated by Django 3.2.23 on 2023-12-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_mingle_app', '0002_edituserdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edituserdetail',
            name='display_pic',
        ),
    ]
