# Generated by Django 3.2.23 on 2023-12-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_mingle_app', '0002_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='event',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
