# Generated by Django 3.2.23 on 2023-12-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_mingle_app', '0006_auto_20231218_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradetails',
            name='phone_num',
            field=models.CharField(max_length=20),
        ),
    ]
